version: "3"
services:
  django:
    restart: always
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
      - elasticsearch
  postgres:
    image: postgres:10.1-alpine
    environment:
      POSTGRES_USER: bergi
  elasticsearch:
    image: elasticsearch:5-alpine
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
