version: "3"
services:
  web:
    restart: always
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
  db:
    image: postgres:10.1-alpine
    environment:
      POSTGRES_USER: bergi
